[package]
name = "levelexperience-tut"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A simple library to create level concepts."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
